version: "3.7"
services:
 
 # Banco de dados usado pela aplicacao
 postgres_cadastro:
  container_name: postgres_cadastro_ifood 
  image: postgres:12.2
  environment:
   POSTGRES_USER: cadastro
   POSTGRES_PASSWORD: cadastro
  ports:
   - 5432:5432

 postgres_marketplace:
  container_name: postgres_marketplace_ifood 
  image: postgres:12.2
  environment:
   POSTGRES_USER: marketplace
   POSTGRES_PASSWORD: marketplace
  ports:
   - 5433:5432
 
 # Para geracao do token
 keycloak_ifood:
  container_name: keycloak_ifood
  image: jboss/keycloak:13.0.0
  environment:
   KEYCLOAK_USER: admin
   KEYCLOAK_PASSWORD: admin
  ports:
   - 8180:8080

 # Para monitoramento do servico, tempo de resposta (Tracing)
 jaeger_ifood:
  container_name: jaeger_ifood
  image: jaegertracing/all-in-one:1.22
  ports:
   - 5775:5775/udp
   - 6831:6831/udp
   - 6832:6832/udp
   - 5778:5778
   - 16686:16686
   - 14268:14268
   - 14250:14250
   - 9411:9411

 # Para metricas e vinculacao a uma dashborad (Grafana)
 prometheus_ifood:
  container_name: prometheus_ifood
  image: prometheus-ifood
  ports:
   - 9090:9090

 # Para geracao de dashboards
 grafana_ifood:
  container_name: grafana_ifood
  image: grafana/grafana:6.5.0
  ports:
   - 3000:3000

# Para mensageria, comunicacao entre bancos
 artemis_ifood:
  container_name: artemis_ifood
  image: vromero/activemq-artemis:2.11.0
  #network_mode: "host"
  environment: 
   ARTEMIS_USERNAME: admin
   ARTEMIS_PASSWORD: admin
  ports:
   - "8161:8161"
   - "61616:61616"
   - "5672:5672"
